services:
  - type: web
    name: erc-insight
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erc-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production

databases:
  - name: erc-database
    databaseName: erc_database
    plan: free